// @ts-check
/**
 * **THE NOTICE SAID THE PACKAGE CONTAINS NO CLDR DATA WHILE 271,797 BYTES OF IT SHIPPED.**
 *
 * `NOTICE` carried a staged placeholder — "No CLDR-derived data is present in this package yet. This
 * notice is staged so that the first build to include it cannot ship without one." That build landed
 * several milestones ago. The placeholder stated its own purpose and then failed at it, which is the
 * self-asserting-text shape this project has now recorded seventeen times, in the one file whose
 * accuracy is a licensing question rather than a documentation one.
 *
 * **NOTHING COULD HAVE CAUGHT IT, because no gate read `NOTICE` at all.** Every other claim of this
 * size here is derived from an artifact; this one was prose next to a directory nobody compared it
 * to. So the rule below is not "does the notice mention CLDR" — a string match would have passed on
 * the placeholder, which mentions CLDR twice. It is: **ask `npm pack` what actually ships, and
 * require the notice to agree with the answer in both directions.**
 *
 * The version is derived too. `src/data/provenance.js` is generated from the pinned data lock, so
 * the CLDR version the build really carries is a fact, not a number somebody typed into a notice.
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { decode as pinnedProvenance } from "../src/data/provenance.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const notice = readFileSync(join(root, "NOTICE"), "utf8");

/** What `npm pack` would actually publish — the artifact a consumer receives, not the working tree. */
const packed = JSON.parse(
  // `--ignore-scripts`, and it is a RACE FIX rather than a preference. `prepack` now runs
  // `npm run types`, so a bare `npm pack` regenerates `types/` — and `node --test` runs files
  // concurrently, so two packing tests plus every test that READS `types/` can meet a
  // half-written directory. Observed once as a single intermittent red in a full run that
  // passed three times after. These two call sites want the FILE LIST, which needs no
  // regeneration; the two tools that want a real tarball (`bundle-sizes`, `readme-newcomer`)
  // run as their own `verify` steps and MUST keep the hook.
  execFileSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"], { cwd: root, encoding: "utf8" }),
)[0];

/**
 * Every packed file that carries generated CLDR-derived data — DERIVED FROM THE NOTICE THE
 * GENERATOR STAMPS INTO IT, not from a path prefix.
 *
 * The prefix version counted `src/data/` plus `src/internal/locale-cldr*` and was wrong in both
 * directions. It swept in `src/data/iana-range-equivalents.js`, whose own generator says in its
 * first paragraph that it is not CLDR data — it encodes IANA registry equivalences — and
 * the two public wrapper modules, which are classifier logic; and it counted
 * `src/internal/locale-cldr.js`, which is 17 KB of port logic whose only string constants are the
 * CLDR sentinels `root`, `und`, `zzzz` and `zz`. On the strength of that filter the NOTICE claimed
 * 19 files and 282,587 bytes; the real answer is the fifteen modules below.
 *
 * **IT KEYS ON PROVENANCE, NOT ON THE ATTRIBUTION, AND AN ABLATION IS WHY.** The first version
 * derived the set from the copyright stamp — which is circular, because the stamp is the thing
 * being required. Measured: reverting the generator to the old `//` attribution emptied the set, so
 * every per-file assertion below became trivially true and only the anti-vacuity floor fired,
 * reporting "the derivation is broken" for a package whose derivation was fine and whose
 * attribution had gone. Keyed on the generator's own provenance line instead, the same mutation
 * fails on the assertion that names the defect.
 *
 * Keying on the marker rather than the location also means a sixteenth generated module is covered
 * the day it is generated, and a module that stops being generated leaves the set by itself.
 */
const CLDR_STAMP = "Copyright (c) 1991-2025 Unicode, Inc. All rights reserved.";
const CLDR_PROVENANCE = "Generated by tools/gen-data.js from pinned CLDR";
const cldrFiles = packed.files.filter((/** @type {{ path: string }} */ f) =>
  f.path.startsWith("src/") && readFileSync(join(root, f.path), "utf8").includes(CLDR_PROVENANCE));

test("if CLDR-derived data ships, the NOTICE says so — and if it does not, it says that", () => {
  const bytes = cldrFiles.reduce((total, /** @type {{ size: number }} */ f) => total + f.size, 0);

  // ANTI-VACUITY FIRST. With no CLDR files in the tarball every assertion below is trivially
  // satisfiable, and this package has shipped that data since M5b — so a zero here means the
  // DERIVATION broke, not that the notice is right.
  // A FLOOR AT TODAY'S COUNT, which is this project's rule — and the first version of it was set
  // from a number I had counted with a looser pattern (`/data/`, which also matched the emitted
  // `types/data/`). It said 36 files where the real answer is 19, and this assertion is what caught
  // it. The figure in NOTICE was corrected from the same measurement.
  // **THE BYTE FLOOR MOVED DELIBERATELY IN M-R S8, FROM 200,000 TO 70,000, AND THE DATA DID NOT
  // SHRINK.** `likely-subtags.js` was re-encoded structurally — 7,788 rows in 25 KB of source
  // instead of 158 KB, decoding to output byte-identical to the pinned CLDR artifact — so the same
  // fifteen modules now weigh 75,795 packed bytes rather than 208,948. The FILE floor is the term
  // that still bites: a module losing its attribution leaves the set, which is what this catches.
  // Set at today's count, per this project's floors-not-exact-counts rule.
  assert.ok(cldrFiles.length >= 15 && bytes > 70_000,
    `only ${cldrFiles.length} CLDR-derived file(s) / ${bytes} bytes found in the tarball. ` +
    "Either the derivation is broken or the generated modules have stopped carrying the " +
    "attribution — the set is keyed on the stamp, so losing the stamp empties it, and an empty set " +
    "makes every per-file assertion below trivially true. Ablated: reverting the generator to a " +
    "`//` attribution reports exactly this.");

  assert.match(notice, /This package INCLUDES data derived from Unicode CLDR/,
    "the package ships CLDR-derived data and the NOTICE must say so affirmatively");

  // THE DENIAL, IN BOTH THE SPELLINGS THAT MATTER. The placeholder is the one that actually shipped;
  // the general form catches a future rewrite that reintroduces the claim in different words.
  assert.doesNotMatch(notice, /No CLDR-derived data is present/i,
    "the NOTICE denies carrying data the tarball contains");
  assert.doesNotMatch(notice, /will include data derived from Unicode CLDR/i,
    "the NOTICE describes shipping CLDR data as a future event; it is present tense now");
});

test("the CLDR version the NOTICE states is the version the build actually carries", () => {
  // DERIVED, not transcribed. `provenance.js` is generated from the pinned data lock, so this fails
  // the day the pinned data moves and the notice does not — which is exactly when a licensing
  // notice naming the wrong release stops being a formality.
  const { cldrVersion } = pinnedProvenance();
  assert.match(cldrVersion, /^\d+(?:\.\d+)*$/, "the pinned provenance is not version-shaped");
  assert.ok(notice.includes(`Unicode CLDR ${cldrVersion}`),
    `the NOTICE must name the CLDR version this build carries (${cldrVersion})`);
  assert.ok(notice.includes(`release-${cldrVersion.replace(".", "-")}`),
    "the NOTICE's source link must point at the release the build was generated from");
});

test("the NOTICE and the LICENSE are both in the published tarball", () => {
  // A notice that is correct and unshipped is worth nothing: Unicode License v3 requires it to
  // ACCOMPANY the data. `package.json#files` is what decides, and it is editable in one line.
  const paths = packed.files.map((/** @type {{ path: string }} */ f) => f.path);
  for (const required of ["NOTICE", "LICENSE"])
    assert.ok(paths.includes(required), `${required} must be in the published package`);
});

/**
 * THE PERMISSION NOTICE HAD TO TRAVEL, AND THE TEST BELOW USED TO STATE THAT AND CHECK SOMETHING
 * WEAKER.
 *
 * Its comment read "A notice that is correct and unshipped is worth nothing: Unicode License v3
 * requires it to ACCOMPANY the data" — and then asserted only that `NOTICE` and `LICENSE` are in the
 * tarball. Neither contains the permission notice. `NOTICE` said the text "accompanies this data and
 * is reproduced in THIRD-PARTY-NOTICES.md in the lokalized-spec repository", which is a file in
 * ANOTHER repository that nobody who runs `npm install lokalized` receives. So the gate named the
 * obligation correctly and then checked a weaker thing, one layer above the self-asserting texts it
 * was written to stop.
 *
 * The licence's own grant is what makes this checkable rather than a matter of taste: it is
 * conditional on the copyright and permission notice appearing "with all copies of the Data Files or
 * Software, or ... in associated Documentation". Whether a given arrangement satisfies a licence is
 * not a question a test can answer; whether the text is in the tarball at all is, and it was not.
 */
const PERMISSION_NOTICE_OPENING =
  "Permission is hereby granted, free of charge, to any person obtaining a";

test("the Unicode permission notice is published WITH the data, not pointed at in another repository", () => {
  const paths = packed.files.map((/** @type {{ path: string }} */ f) => f.path);
  assert.ok(paths.includes("THIRD-PARTY-NOTICES.md"),
    "the package ships CLDR-derived data and the Unicode permission notice is not in the tarball");

  const notices = readFileSync(join(root, "THIRD-PARTY-NOTICES.md"), "utf8");
  assert.ok(notices.includes(PERMISSION_NOTICE_OPENING),
    "THIRD-PARTY-NOTICES.md ships but does not contain the permission notice itself");
  assert.ok(notices.includes("SPDX-License-Identifier: Unicode-3.0"),
    "the shipped notices name no licence identifier");

  // BOTH DISCLAIMERS, because a truncated copy of a licence is not that licence and would be the
  // easiest way for this file to drift into a summary.
  assert.ok(notices.includes("THE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\""),
    "the shipped licence text is missing its warranty disclaimer");
  assert.ok(notices.includes("Except as contained in this notice, the name of a copyright holder"),
    "the shipped licence text is missing its trademark clause");
});

test("NOTICE points only at files a consumer actually receives", () => {
  const paths = new Set(packed.files.map((/** @type {{ path: string }} */ f) => f.path));

  // **DERIVED, AND THE FIRST VERSION WAS AN ALLOWLIST OF THE ANSWER.** Its comment claimed "every
  // capitalised file-shaped token the notice names must be in the tarball" and then filtered the
  // matches down to four names it already expected — so everything else was discarded unchecked.
  // An adversarial pass planted pointers to `CLDR-DATA.txt` and `DATA-MANIFEST.json`, neither of
  // which exists, and the file passed 8/8. A gate that only checks the tokens it was told to expect
  // is the shape this repository keeps finding, written into the gate built to stop it.
  //
  // The rule now keys on SHAPE — anything with a file extension, plus the two extensionless names a
  // package ships — and every one of them must be in the tarball.
  // `xml` is in the set so the CLDR source files count as named — they are the largest group of
  // file-shaped tokens in the notice, and leaving them out made the upstream floor below read 1
  // where it should read 8.
  const EXTENSIONS = /\.(?:md|txt|json|js|mjs|ts|xml)$/;
  const named = [...notice.matchAll(/(?:^|[\s`'"(])([A-Za-z0-9][A-Za-z0-9._/-]*)(?=[\s`'".,;)]|$)/gm)]
    .map((match) => match[1].replace(/[.,;]$/, ""))
    .filter((token) => EXTENSIONS.test(token) || /^(?:LICENSE|NOTICE)$/.test(token));

  // UPSTREAM SOURCE PATHS ARE NOT PACKAGE FILES. `common/properties/scriptMetadata.txt` and its
  // siblings name files in the CLDR release the data was generated FROM; requiring them in the
  // tarball would demand the package vendor CLDR. The exemption is asserted non-empty, or it is dead
  // machinery the day the notice stops citing its sources.
  const upstream = named.filter((token) => token.startsWith("common/"));
  assert.ok(upstream.length >= 4,
    `NOTICE cites ${upstream.length} upstream CLDR source path(s); it must say what the data came from`);

  const ours = named.filter((token) => !token.startsWith("common/"));
  assert.ok(ours.length >= 3, `NOTICE names ${ours.length} file(s) of this package; the derivation is broken`);
  for (const token of new Set(ours))
    assert.ok(paths.has(token), `NOTICE names ${token}, which is not in the published tarball`);

  assert.doesNotMatch(notice, /in the lokalized-spec repository/,
    "NOTICE sends a consumer to a repository they do not have for the licence text");
});

test("every CLDR-derived module carries the attribution a minifier keeps", () => {
  // **A `//` LINE IS NOT AN ATTRIBUTION ONCE ANYTHING MINIFIES IT.** Measured before this changed:
  // a minified bundle of `src/index.js` was 322,205 bytes, carried the CLDR data, and contained the
  // word `copyright` ZERO times. `/*!` is the form bundlers preserve. The pointer has to be in the
  // comment as well, or the artifact carries a copyright line and no way to reach the terms.
  // **BOTH PRESERVED FORMS ARE ACCEPTED, and an adversarial pass is why.** The rule required `/*!`
  // and rejected `//!` — which every one of these bundlers also keeps, measured across six comment
  // forms: `/*!`, `//!`, `@license` and `@preserve` survive minification and a plain `/*` or `//`
  // does not. With `//!` banners this file failed while `npm run check:bundle` reported the notice
  // present, so the two gates disagreed about the same artifact and the bundle gate was right.
  const PRESERVED = /^(?:\/\*![^]*?\*\/|(?:\/\/!.*\n)+)/;
  for (const file of cldrFiles) {
    const text = readFileSync(join(root, file.path), "utf8");
    assert.match(text, PRESERVED,
      `${file.path} carries CLDR-derived data and opens with no preserved legal comment`);
    const legal = /** @type {RegExpMatchArray} */ (text.match(PRESERVED))[0];
    assert.ok(legal.includes(CLDR_STAMP), `${file.path}'s legal comment omits the copyright line`);
    assert.ok(legal.includes("THIRD-PARTY-NOTICES.md"),
      `${file.path}'s legal comment does not say where the licence text is`);
  }

  // IDENTICAL IN EVERY MODULE, WHICH IS WHAT MAKES IT AFFORDABLE. esbuild deduplicates identical
  // legal comments — measured, three modules with one banner produce one copy — so the attribution
  // costs a bundle one copy however many generated modules it pulls in. Any per-file detail in the
  // comment would defeat that silently, and the bundle would carry fifteen copies with nothing
  // saying so.
  const banners = new Set(cldrFiles.map((/** @type {{ path: string }} */ f) =>
    /** @type {RegExpMatchArray} */ (readFileSync(join(root, f.path), "utf8").match(PRESERVED))[0]));
  assert.equal(banners.size, 1,
    `the ${cldrFiles.length} CLDR modules carry ${banners.size} different legal comments; a bundler ` +
    "deduplicates only identical ones, so each distinct spelling is another copy in every artifact");
});

test("the NOTICE's file count is the count that ships", () => {
  // The old notice said "19 files" from a path-prefix filter that swept in a JDK-derived module and
  // 17 KB of port logic. A number in a licensing notice is a claim like any other.
  const stated = /\b(fifteen|sixteen|seventeen|eighteen|nineteen|twenty|\d+)\s+modules\b/.exec(notice);
  assert.ok(stated, "NOTICE states no module count for the CLDR-derived data");
  const words = { fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20 };
  const claimed = words[/** @type {keyof typeof words} */ (stated[1])] ?? Number(stated[1]);
  assert.equal(claimed, cldrFiles.length,
    `NOTICE claims ${claimed} CLDR-derived modules and ${cldrFiles.length} ship`);
});

/**
 * THE IANA MODULES, derived from their generator's own provenance line rather than listed, so a third
 * IANA module is covered the day it is generated — the same keying the CLDR set above uses, for the
 * reason its header records.
 */
const IANA_PROVENANCE = "Generated by tools/gen-iana-data.js";
const ianaFiles = packed.files.filter((/** @type {{ path: string }} */ f) =>
  f.path.startsWith("src/") && readFileSync(join(root, f.path), "utf8").includes(IANA_PROVENANCE));

test("the modules the NOTICE excludes from CLDR really are not CLDR", () => {
  // THE ANTI-VACUITY ARM FOR THE CORRECTION. `iana-range-equivalents.js` was swept into the CLDR
  // count by an old filter; the notice says the IANA modules are not CLDR data. If one ever starts
  // carrying the CLDR stamp, that sentence is wrong and this fails rather than the exclusion going
  // quiet. Two since A30: the full table behind `lokalized/negotiate`, and the direct-match
  // projection the root reads.
  assert.deepEqual(ianaFiles.map((/** @type {{ path: string }} */ f) => f.path).sort(),
    ["src/data/iana-identity-equivalents.js", "src/data/iana-range-equivalents.js"],
    "the tarball's IANA-generated modules are not the two the notices describe");
  for (const iana of ianaFiles) {
    // **ASKED OF THE MODULE'S OWN TEXT, not of its membership in `cldrFiles`.** That set is keyed on
    // the `gen-data.js` provenance marker, which these modules can never carry, so a membership test
    // is vacuous by construction. Measured: with the membership form, planting the CLDR copyright on
    // the module left the whole file at exit 0. The claim NOTICE makes is about the ATTRIBUTION.
    assert.ok(!readFileSync(join(root, iana.path), "utf8").includes(CLDR_STAMP),
      `NOTICE says ${iana.path} is not CLDR data and it now carries the CLDR attribution`);
    assert.ok(notice.includes(`\`${iana.path}\``), `NOTICE does not name ${iana.path}`);
  }
  assert.match(notice, /are NOT CLDR data/,
    "NOTICE no longer distinguishes the IANA modules from the CLDR ones");
});

/**
 * THE SHIPPED LICENCE TEXT AGAINST THE CANONICAL ONE, BYTE FOR BYTE.
 *
 * The assertions above check that the disclaimer and the trademark clause are present, which catches
 * a licence that has been summarised away. They do not catch a licence that has been REWORDED, and a
 * reworded licence is not that licence. The spec repository holds the copy this project pins; this
 * compares the two from `UNICODE LICENSE V3` onward, which is the part that must not be touched. The
 * preamble above it is deliberately different in each repository, because it describes a different
 * artifact — the spec's names `vendor/lokalized-java/` paths that no npm consumer has.
 *
 * SKIPPED without the sibling checkout, on this repository's standing convention for corpus-driven
 * tests: it is the right answer for a bare local clone and the wrong one for CI, which checks both
 * repositories out and then FAILS if any test skips.
 */
const specNotices = process.env.LOKALIZED_SPEC_DIR
  ? join(process.env.LOKALIZED_SPEC_DIR, "THIRD-PARTY-NOTICES.md")
  : join(root, "../lokalized-spec/THIRD-PARTY-NOTICES.md");
const specNoticesMissing = !existsSync(specNotices);

test("the licence text this package ships is the pinned one, unaltered", { skip: specNoticesMissing }, () => {
  const licenceOf = (/** @type {string} */ text) => {
    const at = text.indexOf("UNICODE LICENSE V3");
    assert.notEqual(at, -1, "no Unicode License v3 block found");
    return text.slice(at).trimEnd();
  };
  const canonical = licenceOf(readFileSync(specNotices, "utf8"));
  const shipped = licenceOf(readFileSync(join(root, "THIRD-PARTY-NOTICES.md"), "utf8"));

  // ANTI-VACUITY: two empty strings compare equal, and a heading whose spelling drifted would give
  // exactly that. The floor is today's length.
  assert.ok(canonical.length > 1_500, `the canonical licence block is ${canonical.length} bytes; the extraction is broken`);
  assert.equal(shipped, canonical,
    "the licence text in this package is not byte-identical to the pinned copy in lokalized-spec");
});

test("THIRD-PARTY-NOTICES.md's own claims are the ones that ship", () => {
  // **THE FILE THIS SLICE ADDED SHIPPED THREE FALSE SENTENCES, and an auditor found all three.**
  // It said `npm pack` carries "the pinned locale table under `src/internal/`" — there is none; that
  // it and `src/internal/locale-cldr.js` "encode plural rules, ordinal rules, …" — that module
  // imports every table it uses and embeds nothing, which THIS FILE'S OWN comment says thirty lines
  // up; and that "every generated module carries this notice", where sixteen are generated and
  // fifteen are stamped. NOTICE was corrected in the same change and this file was not, which is the
  // two-copies-of-one-claim shape that put `LocaleMatch` in two subpaths disagreeing.
  const notices = readFileSync(join(root, "THIRD-PARTY-NOTICES.md"), "utf8");

  const stated = /\b(fifteen|sixteen|seventeen|\d+)\s+(?:generated\s+)?modules\b/.exec(notices);
  assert.ok(stated, "THIRD-PARTY-NOTICES.md states no module count");
  const words = { fifteen: 15, sixteen: 16, seventeen: 17 };
  const claimed = words[/** @type {keyof typeof words} */ (stated[1])] ?? Number(stated[1]);
  assert.equal(claimed, cldrFiles.length,
    `THIRD-PARTY-NOTICES.md claims ${claimed} CLDR-derived modules and ${cldrFiles.length} ship`);

  // The two sentences that were wrong, in the general form rather than verbatim, so a reworded
  // version of the same mistake is caught too.
  assert.doesNotMatch(notices, /pinned (?:locale )?tables? under `src\/internal\//,
    "THIRD-PARTY-NOTICES.md claims CLDR tables under src/internal/; measured, there are none");
  assert.doesNotMatch(notices, /[Ee]very generated module carries/,
    "THIRD-PARTY-NOTICES.md says every GENERATED module carries the CLDR notice; the JDK-derived " +
    "one is generated and must not");

  // Each lineage the package carries is named. The floor is today's set, and each is a section.
  for (const heading of ["## Unicode CLDR", "## IANA language range equivalents", "## minimal-json"])
    assert.ok(notices.includes(heading), `THIRD-PARTY-NOTICES.md has no ${heading} section`);
});

/**
 * **THE IANA PROVENANCE SENTENCES IN THE THREE SHIPPED PROSE SURFACES, DERIVED RATHER THAN
 * RESTATED.**
 *
 * The provenance of this data has moved three times — probed out of the JDK's
 * `LanguageRange.parse`, then out of lokalized-java's own table (M-R S13), then GENERATED from the
 * registry snapshot with no JDK (A30) — and `NOTICE`, `THIRD-PARTY-NOTICES.md` and `README.md` all
 * describe it and all three SHIP. After M-R S13 not one of them was re-derived, so for a day the
 * package told every consumer its language data came from a JDK build, named an entry count 12 short,
 * and (in THIRD-PARTY-NOTICES, the licensing surface) denied a registry snapshot the artifact
 * recorded. `check:readme` cannot see prose at all, which S12 recorded. This is the standing lesson in
 * its own words — a document that ships is a surface, and its second copy drifts like any other.
 *
 * Every number below comes from the shipped modules. The prose may say more than this; what it may
 * not do is contradict the data it ships beside, or describe a provenance that no longer exists.
 */
const surfaces = [
  { path: "NOTICE", text: notice },
  { path: "THIRD-PARTY-NOTICES.md", text: readFileSync(join(root, "THIRD-PARTY-NOTICES.md"), "utf8") },
  { path: "README.md", text: readFileSync(join(root, "README.md"), "utf8") },
];

test("the shipped IANA provenance prose describes the registry-generated data, and none of the retired provenance", async () => {
  // Keyed on the generated module's own header, which gen-iana-data.js writes from the artifact: if
  // the data stops being registry-generated, the header says so and this rule has to be re-aimed
  // rather than passing over prose that has become true again.
  const header = readFileSync(join(root, "src/data/iana-range-equivalents.js"), "utf8");
  assert.match(header, /Source: the IANA Language Subtag Registry, File-Date \d{4}-\d{2}-\d{2}/,
    "the generated module no longer names the registry snapshot as its source; re-aim this rule");
  assert.match(header, /generated there with no JDK/);

  // The retired claims, in the shapes the three surfaces carried them: the data being the JDK's own
  // `LanguageRange.parse` output, being RECORDED BY PROBING an implementation, being verified by
  // RECONSTRUCTION against override rows, and the probed closure's own size.
  const retired = [
    /LanguageRange\.parse[^.]{0,120}\b(?:pinned )?OpenJDK/,
    /equivalence data[^.]{0,40}is \*\*the JDK's\*\*/,
    /\b(?:recorded|derived) by (?:exhaustively )?probing\b/i,
    /verified\s+by\s+reconstruction/i,
    /\b818 language\b/,
  ];
  for (const surface of surfaces)
    for (const claim of retired)
      assert.equal(claim.test(surface.text), false,
        `${surface.path} still states the retired IANA provenance ${claim}: the data is generated ` +
        "from the registry snapshot with no JDK (A30). Re-derive the paragraph from the artifact.");
});

test("the shipped IANA provenance prose states the counts the package actually ships, wherever it states them", async () => {
  const { decodeLanguageEquivalents } = await import("../src/data/iana-range-equivalents.js");
  const table = decodeLanguageEquivalents();
  const subtags = table.size;
  // A class is a key plus its others, so the distinct classes are the distinct SORTED member sets.
  const classes = new Set([...table].map(([key, others]) => JSON.stringify([key, ...others].sort()))).size;
  assert.ok(subtags > 100 && classes > 100, `the table decoded to ${subtags} subtags in ${classes} classes; the probe is not reading it`);

  // Keyed on the SHAPE of the claim rather than on one file, so a count appearing in another
  // surface is caught too.
  const claim = /encodes ([\d,]+) language\s+subtags\s+in\s+([\d,]+)\s+equivalence\s+classes/;
  let stated = 0;
  for (const surface of surfaces) {
    const found = claim.exec(surface.text);
    if (found === null) continue;
    stated++;
    assert.deepEqual([Number(/** @type {string} */ (found[1]).replace(/,/g, "")), Number(/** @type {string} */ (found[2]).replace(/,/g, ""))],
      [subtags, classes], `${surface.path} says ${found[1]} subtags in ${found[2]} classes; it ships ${subtags} in ${classes}`);
  }
  assert.ok(stated > 0,
    "no shipped surface states the table's size any more — either the sentence was reworded out from " +
    "under this rule, or the attribution stopped being quantified. Re-aim it.");
});

/**
 * **THE SECOND MODULE'S COUNTS SHIPPED UNGATED.** The rule above keys on "encodes N language subtags
 * in M equivalence classes", which is the FULL table's sentence; the same paragraph also states the
 * direct-match projection's size and the number of region/variant substitutions, and nothing read
 * either. Measured: rewriting them to "250 subtags in 120 classes" and "15 region" left all 1,723
 * tests green. So every "N subtags in M classes" a shipped surface states must be one of the two
 * tables the package ships, the parenthesised projection figure must be the projection's, and every
 * substitution count must be the module's — each derived from the modules, never typed.
 */
test("the shipped IANA prose states the projection's counts and the substitution count the package ships, wherever it states them", async () => {
  const { decodeLanguageEquivalents } = await import("../src/data/iana-range-equivalents.js");
  const { decodeIdentityEquivalents, decodeRegionVariantEquivalents } = await import("../src/data/iana-identity-equivalents.js");
  const classesOf = (/** @type {Map<string, string[]>} */ table) =>
    new Set([...table].map(([key, others]) => JSON.stringify([key, ...others].sort()))).size;
  const full = decodeLanguageEquivalents();
  const projection = decodeIdentityEquivalents();
  const tables = { full: [full.size, classesOf(full)], projection: [projection.size, classesOf(projection)] };
  const substitutions = decodeRegionVariantEquivalents().length;
  // ANTI-VACUITY: a projection as large as the table, or an empty one, would make the two
  // alternatives below indistinguishable or trivially unmatched.
  assert.ok(projection.size > 100 && projection.size < full.size && substitutions > 5,
    `decoded ${projection.size} projection subtags of ${full.size} and ${substitutions} substitutions; the probe is not reading the modules`);

  const number = (/** @type {string} */ text) => Number(text.replace(/,/g, ""));
  let projectionStated = 0;
  let substitutionsStated = 0;
  for (const surface of surfaces) {
    const flat = surface.text.replace(/\s+/g, " ");
    for (const match of flat.matchAll(/([\d,]+) (?:language )?subtags in ([\d,]+) (?:equivalence )?classes/g)) {
      const stated = JSON.stringify([number(/** @type {string} */ (match[1])), number(/** @type {string} */ (match[2]))]);
      assert.ok(stated === JSON.stringify(tables.full) || stated === JSON.stringify(tables.projection),
        `${surface.path} says "${match[0]}"; the package ships ${tables.full[0]} subtags in ${tables.full[1]} classes (full table) ` +
        `and ${tables.projection[0]} in ${tables.projection[1]} (the direct-match projection)`);
    }
    for (const match of flat.matchAll(/\(([\d,]+) subtags in ([\d,]+) classes\)/g)) {
      projectionStated++;
      assert.deepEqual([number(/** @type {string} */ (match[1])), number(/** @type {string} */ (match[2]))], tables.projection,
        `${surface.path} states the projection as "${match[0]}"; it ships ${tables.projection[0]} subtags in ${tables.projection[1]} classes`);
    }
    for (const match of flat.matchAll(/\b([\d,]+) region (?:and |\/ ?)variant substitutions/gi)) {
      substitutionsStated++;
      assert.equal(number(/** @type {string} */ (match[1])), substitutions,
        `${surface.path} says "${match[0]}"; the package ships ${substitutions}`);
    }
  }
  assert.ok(projectionStated > 0 && substitutionsStated > 0,
    `no shipped surface states the projection's size (${projectionStated}) or the substitution count (${substitutionsStated}) any ` +
    "more; either the sentence was reworded out from under this rule or the attribution stopped being quantified. Re-aim it.");
});

/**
 * **THE IANA SECTION OF THE LICENSING NOTICE STATES THE SOURCE, THE SNAPSHOT AND WHAT IS DERIVED — AND
 * NOTHING ABOUT THE REGISTRY'S LEGAL STATUS.** A sentence calling the registry "factual data rather
 * than a licensed work" shipped in both notices with no source, measurement or decision behind it: an
 * uncited licensing claim in the licensing surface. The maintainer's decision (2026-09-23) is that the
 * section states only the source URL, the pinned snapshot's File-Date and SHA-256, and what the package
 * derives from it. The File-Date and SHA-256 are derived from what the build carries, so the section
 * goes stale the day the snapshot moves.
 */
test("THIRD-PARTY-NOTICES.md's IANA section names the pinned snapshot and does not characterise the registry's legal status", async () => {
  const notices = readFileSync(join(root, "THIRD-PARTY-NOTICES.md"), "utf8");
  const heading = "## IANA language range equivalents";
  const start = notices.indexOf(heading);
  assert.notEqual(start, -1, `THIRD-PARTY-NOTICES.md has no ${heading} section`);
  const end = notices.indexOf("\n## ", start + heading.length);
  const section = notices.slice(start, end === -1 ? undefined : end).replace(/\s+/g, " ");

  const { RUNTIME_METADATA } = await import("../src/internal/runtime-metadata.js");
  const header = readFileSync(join(root, "src/data/iana-range-equivalents.js"), "utf8");
  const digest = /File-Date (\d{4}-\d{2}-\d{2}), sha256 ([0-9a-f]{64})/.exec(header);
  assert.ok(digest, "the generated module no longer records the snapshot's File-Date and sha256; re-aim this rule");
  assert.equal(digest[1], RUNTIME_METADATA.ianaRegistryDate, "the generated module and the runtime metadata name different snapshots");

  for (const [what, needle] of [
    ["the registry's source URL", "https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry"],
    ["the pinned snapshot's File-Date", `File-Date \`${digest[1]}\``],
    ["the pinned snapshot's SHA-256", digest[2]],
  ])
    assert.ok(section.includes(/** @type {string} */ (needle)), `THIRD-PARTY-NOTICES.md's IANA section does not state ${what} (${needle})`);

  const characterisation = /licen[cs]ed work|factual data|public domain|no licen[cs]e|not copyright|copyrightable/i.exec(section);
  assert.equal(characterisation, null,
    `THIRD-PARTY-NOTICES.md's IANA section characterises the registry's legal status ("${characterisation?.[0]}"); ` +
    "it states only the source, the pinned snapshot and what the package derives from it");
});

test("the shipped IANA provenance prose does not deny the registry snapshot the artifact records", async () => {
  const { RUNTIME_METADATA } = await import("../src/internal/runtime-metadata.js");
  const date = RUNTIME_METADATA.ianaRegistryDate;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return;   // no snapshot pinned; nothing to contradict

  // THIRD-PARTY-NOTICES.md said "it carries no registry file date because there is no registry
  // snapshot behind it" for a day after one was pinned. That is the licensing surface denying
  // the provenance of the data in the same tarball.
  const denial = /no registry file date|there is no registry snapshot|pinned to a JDK build rather than/i;
  for (const surface of surfaces)
    assert.equal(denial.test(surface.text), false,
      `${surface.path} denies a registry snapshot while the build records File-Date ${date}`);
});
