// @ts-check
import { builtinModules } from "node:module";
import { execFileSync } from "node:child_process";
import { withoutComments } from "../tools/graph-walk.mjs";
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../", import.meta.url);
const pkg = JSON.parse(await readFile(new URL("package.json", root), "utf8"));

/**
 * The nine entry points documented in IMPLEMENTATION-PLAN-v7.md section 3.1 (internal; see ../planning/).
 * This list is intentionally hand-written: it is the contract, and the export
 * map is the implementation of it. Deriving one from the other would let both
 * drift together silently.
 */
const DOCUMENTED_SUBPATHS = [
  ".",
  "./core",
  "./parse",
  "./load",
  "./ssr",
  "./negotiate",
  "./node",
  "./data/ordinal",
  "./data/ranges",
];

test("export map matches the documented entry points exactly", () => {
  const exported = Object.keys(pkg.exports).filter((k) => k !== "./package.json");
  assert.deepEqual(exported.sort(), [...DOCUMENTED_SUBPATHS].sort());
});

test("every documented subpath resolves and imports", async () => {
  for (const subpath of DOCUMENTED_SUBPATHS) {
    const target = pkg.exports[subpath].import;
    assert.ok(target, `${subpath} declares no import target`);
    await assert.doesNotReject(
      () => import(new URL(target, root).href),
      `${subpath} -> ${target} failed to import`,
    );
  }
});

test("every subpath declares types before import", () => {
  // Condition order is significant: "types" must precede "import" or
  // TypeScript's node16/nodenext resolution picks the JS file first.
  for (const subpath of DOCUMENTED_SUBPATHS) {
    const conditions = Object.keys(pkg.exports[subpath]);
    assert.deepEqual(conditions, ["types", "import"], `${subpath} condition order`);
  }
});

test("every published directory is either in git or regenerated before packing", () => {
  // **PUBLISHING FROM A FRESH CLONE WOULD HAVE SHIPPED ZERO TYPESCRIPT DECLARATIONS.** `types/` is
  // in `package.json#files`, is in `.gitignore`, and is tracked by git not at all — it exists on
  // this machine only because somebody ran `npm run types` at some point. Reproduced rather than
  // reasoned about: `git archive HEAD` into a clean directory and `npm pack --dry-run` there packed
  // **0** `types/` entries against 54 from the working tree. Every TypeScript consumer of the first
  // publish from a clean checkout would have got a package with no types at all.
  //
  // The repair is a `prepack` hook, which npm runs for both `npm pack` and `npm publish`. THE RULE
  // BELOW IS THE INVARIANT RATHER THAN THE REPAIR: a published path that git does not carry must be
  // produced by a pre-pack script. That catches the next generated directory somebody adds to
  // `files`, which is the shape this was — nobody chose to ship an empty `types/`, it just followed
  // from two independently reasonable decisions.
  const tracked = (/** @type {string} */ entry) => {
    const listed = execFileSync("git", ["ls-files", "--", entry], { cwd: root, encoding: "utf8" });
    return listed.trim().length > 0;
  };

  const generated = pkg.files.filter((/** @type {string} */ entry) => !tracked(entry));
  assert.ok(generated.length > 0,
    "no published path is generated — if that is now true, this rule is vacuous and should be deleted");
  assert.ok(generated.includes("types/"),
    "the derivation broke: `types/` is generated and must be the case this rule is about");

  for (const entry of generated)
    assert.ok(typeof pkg.scripts?.prepack === "string" && pkg.scripts.prepack.length > 0,
      `'${entry}' is published but not in git, so a fresh clone would publish it EMPTY. ` +
      "It must be regenerated by a `prepack` script, which npm runs for both pack and publish");

  // AND THE HOOK MUST ACTUALLY PRODUCE THEM. A `prepack` running the wrong script satisfies the
  // assertion above and ships the same empty directory.
  assert.match(pkg.scripts.prepack, /\btypes\b/,
    "`prepack` must regenerate the declarations, not merely exist");
});

test("package is ESM-only with no CommonJS contract", () => {
  assert.equal(pkg.type, "module");
  assert.equal(pkg.sideEffects, false);
  assert.ok(pkg.engines?.node, "engines.node is required");
  const serialized = JSON.stringify(pkg.exports);
  assert.ok(!serialized.includes('"require"'), "exports must not declare a require condition");
  assert.ok(!("main" in pkg), 'legacy "main" must not be present');
});

test("no runtime dependencies", () => {
  assert.ok(!pkg.dependencies, "the package must declare no runtime dependencies");
});

/** Recursively collect .js files under a directory. */
async function jsFiles(dir, acc = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) await jsFiles(path, acc);
    else if (entry.name.endsWith(".js")) acc.push(path);
  }
  return acc;
}

test("Node built-ins stay behind lokalized/node", async () => {
  // Plan section 9.1: browser and edge graphs must not reach Node built-ins.
  //
  // WIDENED 2026-09-10, BEFORE M8 gave `src/node/` real Node code, and the order was the point.
  // This scan matched `from "node:..."` and nothing else, so FOUR ways of reaching the same
  // built-ins walked straight past it -- a bare specifier (`from "fs"`), a dynamic
  // `import("node:fs")`, a side-effect `import "node:fs"`, and the Node globals, which need no
  // import at all. MEASURED against the old scan: `from "fs"`, `import("node:fs")` and
  // `process.cwd()` were all MISSED; all three are caught now, with the original `from "node:fs"`
  // still caught as a regression control.
  //
  // WHY IT HAD TO HAPPEN FIRST. `tsc` was catching some of those only BY ACCIDENT: with no
  // `@types/node` installed every Node import is a TS2307. M8 has to make `src/node/` typecheck,
  // and any way of doing that -- the real @types/node or hand-written ambient declarations --
  // makes those imports resolve EVERYWHERE, browser subpaths included. So the accidental gate dies
  // the moment M8 starts, and relying on an accident is what this project criticizes elsewhere.
  //
  // The built-in list is `module.builtinModules`, not a hand-kept array, for the reason every list
  // here is derived where it can be: a hand-kept one silently stops covering a built-in Node adds.
  const builtins = new Set(builtinModules.filter((name) => !name.startsWith("_")));
  const isBuiltin = (specifier) =>
    specifier.startsWith("node:") ? true : builtins.has(specifier.split("/")[0]);

  // Every shape that puts a module in the graph, plus CommonJS `require`, which is not reachable in
  // an ESM package but is exactly the sort of thing a copy-paste brings in.
  const SPECIFIER_PATTERNS = [
    /from\s+["']([^"']+)["']/g,
    /(?:^|[^.\w])import\s+["']([^"']+)["']/gm,
    /import\(\s*["']([^"']+)["']/g,
    /(?:^|[^.\w])require\(\s*["']([^"']+)["']/g,
  ];
  // Globals that only exist in Node. `TextDecoder` is deliberately absent: it is a web standard and
  // the project's constraints permit it.
  const NODE_GLOBALS = ["process", "Buffer", "__dirname", "__filename", "global"];

  const files = await jsFiles(new URL("src", root).pathname);
  const offenders = [];
  for (const file of files) {
    if (file.includes("/src/node/")) continue;
    const source = withoutComments(await readFile(file, "utf8"));
    for (const pattern of SPECIFIER_PATTERNS)
      for (const match of source.matchAll(pattern))
        if (isBuiltin(match[1])) offenders.push(`${file}: imports '${match[1]}'`);

    // Globals are matched on source with STRING LITERALS removed as well, so a message fragment or
    // a locale tag containing the word cannot be mistaken for a reference. Measured: without this,
    // `src/internal/expression.js` trips on the English word "process" inside a sentence.
    const code = source.replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`/g, '""');
    for (const name of NODE_GLOBALS)
      if (new RegExp(`(?<![.\\w$])${name}(?![\\w$])`).test(code))
        offenders.push(`${file}: references the Node global '${name}'`);
  }
  assert.deepEqual(offenders, [], "Node built-ins found outside src/node/");
});

test("legal notices are packed", () => {
  for (const required of ["LICENSE", "NOTICE"]) {
    assert.ok(pkg.files.includes(required), `${required} must be in the files list`);
  }
});

test("the M2 spike is not shipped", () => {
  // Plan v7's M2 gate calls the generated-placeholder spike "throwaway, non-shipping". `files` is an
  // allowlist, so this holds structurally — but the point of the spike is that it is disposable, and
  // an allowlist is one careless addition away from shipping it.
  assert.ok(existsSync(new URL("../spike/generated-placeholders/spike.mjs", import.meta.url)),
    "the spike should exist; M2 requires it");
  for (const entry of pkg.files) {
    assert.ok(!entry.startsWith("spike"),
      `package.json files includes '${entry}': the M2 spike must never be packed`);
  }

  // AND THE SPELLING CHECK ABOVE IS NOT THE CLAIM. `spike/generated-placeholders/README.md` says
  // "nothing here is packed"; this loop reads the ALLOWLIST, and `"./spike/"` does not start with
  // `spike`, nor does `"**/*.mjs"`. Either ships the spike and passes every assertion above — the
  // document's claim was stronger than its own named gate. So the artifact is packed and read.
    // `--ignore-scripts`, and it is a RACE FIX rather than a preference. `prepack` now runs
    // `npm run types`, so a bare `npm pack` regenerates `types/` — and `node --test` runs files
    // concurrently, so two packing tests plus every test that READS `types/` can meet a
    // half-written directory. Observed once as a single intermittent red in a full run that
    // passed three times after. These two call sites want the FILE LIST, which needs no
    // regeneration; the two tools that want a real tarball (`bundle-sizes`, `readme-newcomer`)
    // run as their own `verify` steps and MUST keep the hook.
  const listed = execFileSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"],
    { cwd: new URL("../", import.meta.url).pathname, encoding: "utf8" });
  const files = JSON.parse(listed)[0].files.map((/** @type {{ path: string }} */ f) => f.path);
  assert.ok(files.length > 50, `npm pack listed ${files.length} file(s); the derivation is broken`);
  assert.deepEqual(files.filter((/** @type {string} */ f) => f.split("/")[0] === "spike"), [],
    "the M2 spike reached the packed artifact");
});

/**
 * THE README STATES `files` VERBATIM, AND NOTHING COMPARED THE TWO UNTIL IT WENT STALE.
 *
 * `### Loading from a browser without a bundler` tells a reader what the published package contains
 * by quoting the array: "`package.json`'s `files` is `["src/", "types/", "LICENSE", "NOTICE",
 * "README.md"]`". M-R S5 added `THIRD-PARTY-NOTICES.md` and that sentence was wrong the moment the
 * entry landed — found by grep while making the change, by no gate afterwards.
 *
 * `check:readme` cannot see it: the claim is prose, and M-D S12 recorded the rule it breaks — a
 * claim that CAN be executed and is left in prose is a claim nothing checks. It is executable here
 * because both sides are machine-readable, so the comparison is the repair rather than a cleverer
 * checker.
 */
test("the `files` array the README quotes is the one package.json declares", async () => {
  const manifest = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
  const readme = await readFile(new URL("README.md", root), "utf8");

  const quoted = /`package\.json`'s `files` is `(\[[^`]*\])`/s.exec(readme);
  assert.ok(quoted, "the README no longer quotes `files`; delete this test or restore the sentence");

  // Parsed, not string-compared: the README wraps the array across lines and a whitespace difference
  // is not a claim about the package.
  const stated = JSON.parse(quoted[1].replace(/\s+/g, " "));
  assert.ok(Array.isArray(stated) && stated.length >= 4,
    `the README quotes ${JSON.stringify(stated)}, which is not a plausible file list`);
  assert.deepEqual(stated, manifest.files,
    "the README's `files` list is not what package.json ships");
});
