#!/usr/bin/env node
// @ts-check
/**
 * Production data encoder: pinned CLDR JSON -> runtime JavaScript modules.
 *
 * Reads the SHA-pinned artifacts vendored in the sibling lokalized-spec checkout and emits
 * `src/data/*.js`. This tool carries no CLDR knowledge: every semantic decision was made upstream
 * by CldrDataGenerator, and every encoding decision is recorded in the planning directory's ENCODING-DECISION.md.
 *
 * Guarantees, all verified by `--check`:
 *   - LOSSLESS: each emitted module is imported, decoded, and its canonical JCS projection compared
 *     byte-for-byte against the same projection of the source. Not a shape check — exact bytes.
 *   - Likely subtags additionally preserve every key, the full language-script-region triple, the
 *     presence bit, and absent/unknown behavior. Row absence and a present Latn row stay distinct.
 *   - REPRODUCIBLE: regeneration is byte-identical.
 *
 *   node tools/gen-data.js --write    emit modules
 *   node tools/gen-data.js --check    verify emitted modules are current, lossless and reproducible
 *   node tools/gen-data.js --measure  integrated size table (raw/min-ish/gzip-9/br-q11/br-q5)
 */
import { brotliCompressSync, constants, gzipSync } from "node:zlib";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const specDir = process.env.LOKALIZED_SPEC_DIR
  ? resolve(process.env.LOKALIZED_SPEC_DIR)
  : resolve(root, "../lokalized-spec");
const vendor = join(specDir, "vendor/lokalized-java/src/build/resources/cldr");
const outDir = join(root, "src/data");

if (!existsSync(vendor)) {
  console.error(`cannot find vendored CLDR artifacts at ${vendor}\nclone lokalized-spec as a sibling, or set LOKALIZED_SPEC_DIR`);
  process.exit(2);
}

const locale = JSON.parse(readFileSync(join(vendor, "cldr-locale-data.json"), "utf8"));
const plural = JSON.parse(readFileSync(join(vendor, "cldr-plural-data.json"), "utf8"));

/** Canonical JSON: sorted object keys, no whitespace. Matches the upstream generator exactly. */
const jcs = (value) => {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(jcs).join(",")}]`;
  return `{${Object.keys(value).sort().map((k) => `${JSON.stringify(k)}:${jcs(value[k])}`).join(",")}}`;
};

const js = (v) => JSON.stringify(v);
/**
 * THE ATTRIBUTION IS A LEGAL COMMENT, NOT A `//` LINE, AND THE DIFFERENCE IS WHAT A BUNDLER KEEPS.
 *
 * Until this change every generated module said "Contains data derived from Unicode CLDR … See
 * NOTICE" on a `//` line, which every minifier strips. Measured against the shipped esbuild: a
 * minified bundle of `src/index.js` was 322,205 bytes, carried the CLDR data, and the word
 * `copyright` occurred ZERO times in it. A `/*!` comment is the form bundlers preserve by
 * convention — esbuild, Terser and Rollup all honour it — so the notice now travels into whatever a
 * consumer builds.
 *
 * **IT IS BYTE-IDENTICAL IN EVERY MODULE ON PURPOSE.** esbuild DEDUPLICATES identical legal
 * comments — measured: three modules carrying the same banner produce one copy in the output — so
 * the attribution costs one copy in a bundle however many generated modules it pulls in. Any
 * per-file detail would defeat that, which is why the file-specific line below is a plain comment
 * and the notice above it carries nothing but the notice.
 */
const LEGAL_NOTICE =
  `/*! Contains data derived from Unicode CLDR ${locale.cldrVersion}.\n` +
  ` * Copyright (c) 1991-2025 Unicode, Inc. All rights reserved.\n` +
  ` * Distributed under the Terms of Use in https://www.unicode.org/copyright.html\n` +
  ` * SPDX-License-Identifier: Unicode-3.0\n` +
  ` * The full licence text is THIRD-PARTY-NOTICES.md in this package.\n` +
  ` */\n`;

const banner = (what) =>
  LEGAL_NOTICE +
  `// Generated by tools/gen-data.js from pinned CLDR ${locale.cldrVersion}. Do not edit by hand.\n` +
  `// Source: lokalized-spec vendor/lokalized-java (${what}).\n`;

/* ------------------------------------------------------------------ encoders
 * Selected per the planning directory's ENCODING-DECISION.md, which chose by best Brotli-q5 because
 * dynamic CDN compression is the production-realistic case and the q11 penalty is negligible.
 */

/** Pair table as one flat array. Chosen for likelySubtags and the language/region alias tables. */
const flatPairs = (pairs) =>
  `/** @type {string[]} */\nconst F = ${js(pairs.flatMap((p) => [p.from, p.to]))};\n` +
  `/** @returns {{from: string, to: string}[]} */\n` +
  `export const decode = () => {\n` +
  `  /** @type {{from: string, to: string}[]} */\n  const out = [];\n` +
  `  for (let i = 0; i < F.length; i += 2) out.push({ from: /** @type {string} */ (F[i]), to: /** @type {string} */ (F[i + 1]) });\n` +
  `  return out;\n};\n`;

/**
 * THE LIKELY-SUBTAG MAXIMIZATION TABLE, ENCODED STRUCTURALLY — 7,788 rows in 22 KB of source
 * instead of 158 KB, and **18,665 fewer brotli bytes on the wire, 25% of the whole browser root
 * bundle**. It is the single largest module in every published graph but `lokalized/ssr`, and it
 * was the one table `planning/ENCODING-DECISION.md` never tried a structural encoding for: its
 * three measured candidates (row/object, flat array, columnar) all store the full tag strings and
 * differ only in how they punctuate them.
 *
 * **WHAT THE STRUCTURE IS.** Measured over all 7,788 rows: every `to` is `lang-Script-Region`, and
 * 7,207 rows are the simple shape `lang -> lang-Script-Region` where the key reappears verbatim in
 * the value. Across those there are only 382 distinct `(script, region)` pairs, and the keys are
 * 2-3 lowercase letters in sorted order. So a simple row carries no tag text at all: its key is a
 * position and its value is an index.
 *
 * Three streams, and the size is in the first two:
 *
 * - `KEYS` — a bitset over every possible 2-3 letter lowercase code, base64. The slot for `ab` is
 *   `(a*26+b)*27` and for `abc` is that plus `c+1`, which is MONOTONE in lexicographic order, so
 *   walking the bits yields the keys already sorted and the value stream can be positional. An
 *   earlier draft used the flat "676 two-letter slots, then 17,576 three-letter slots" space that
 *   `valid-languages.js` uses; that is NOT sorted order, and `valid-languages` gets away with it
 *   only because it ends in `.sort()`. Here the key order also drives the value sequence, so it
 *   produced a table that decoded to the wrong pairs. Measured: 7,207 keys in 1,880 brotli bytes,
 *   2.1 bits each — below the combinatorial bound for choosing 7,207 of 18,252.
 * - `VALUES` — one pair index per key, in the same order, base-91 printable with an escape.
 *   Measured at 5,479 brotli against an order-0 entropy of 5,352: within 2.4% of its floor.
 * - `PAIRS` — the 382 pairs as fixed 7-character fields, script then region padded to three.
 *
 * The remaining 581 rows keep their text, grouped by shape. Every one of them has a script and
 * region that are ALREADY in the pair alphabet, so they too carry only a language and an index.
 *
 * **THE ENCODING WAS CHOSEN BY MEASUREMENT, INCLUDING THREE NEGATIVE RESULTS.** A columnar form with
 * literal tokens is 15 KB smaller raw and 607 bytes BIGGER after brotli — fixed-width literal
 * columns are exactly the redundancy brotli already models. Packing every stream into base64 is 761
 * bytes worse than this hybrid, because packed bits defeat the entropy coder: the optimum is a
 * binary bitset in base64 BESIDE a text symbol stream brotli can model. And interning the
 * `(script, region)` PAIR beats interning script and region separately by ~800 bytes, because the
 * two columns are correlated — joint entropy 5.94 bits against 6.83 apart.
 *
 * It wins at brotli-q11, brotli-q5 AND gzip-9, so the choice does not depend on what the CDN runs —
 * which is not automatic, and is the non-monotonicity `ENCODING-DECISION.md` warns about.
 *
 * **COSTS, MEASURED RATHER THAN ASSUMED.** Decoding is +2.2 ms on first call, of which ~1.9 ms is
 * recovered by parsing 136 KB less JavaScript: net +0.36 ms on a cold import of the whole bundle.
 * Retained heap goes DOWN by 186 KB, the opposite sign from the `valid-languages` bitset caveat in
 * `ENCODING-DECISION.md`, and for a reason: `locale-cldr.js` keeps the decoded map anyway, so the
 * flat array's 157 KB constant pool was pure duplication held for the process lifetime. `atob` is
 * already in the root bundle from `valid-languages.js`, so no new host dependency.
 */
const SLOT_SPAN = 26 * 26 * 27;

/** The bitset slot of a 2-3 letter lowercase code, monotone in lexicographic order. */
const slotFor = (code) => {
  const a = code.charCodeAt(0) - 97, b = code.charCodeAt(1) - 97;
  return (a * 26 + b) * 27 + (code.length === 3 ? code.charCodeAt(2) - 96 : 0);
};

/** One printable base-91 digit; 92 (backslash) is skipped so the stream needs no escaping. */
const digit91 = (value) => String.fromCharCode(value + 35 >= 92 ? value + 36 : value + 35);

/** A pair index as 1 or 3 digits: 0-89 direct, otherwise the escape 90 and two more digits. */
const encodeIndex = (n) => (n < 90
  ? digit91(n)
  : digit91(90) + digit91(((n - 90) / 91) | 0) + digit91((n - 90) % 91));

const maximizationTable = (pairs) => {
  const SIMPLE = /^[a-z]{2,3}$/;
  const simple = [], exceptional = [];
  for (const row of pairs) {
    const to = row.to.split("-");
    (SIMPLE.test(row.from) && to.length === 3 && to[0] === row.from ? simple : exceptional).push(row);
  }

  /** The `(script, region)` alphabet, shared by both halves. Region is padded to three. */
  const fieldFor = (row) => { const t = row.to.split("-"); return t[1] + (t[2].length === 2 ? `${t[2]} ` : t[2]); };
  const alphabet = [];
  const indexOfPair = new Map();
  for (const row of [...simple, ...exceptional]) {
    const field = fieldFor(row);
    if (!indexOfPair.has(field)) { indexOfPair.set(field, alphabet.length); alphabet.push(field); }
  }

  const bits = new Uint8Array(Math.ceil(SLOT_SPAN / 8));
  for (const row of simple) { const slot = slotFor(row.from); bits[slot >> 3] |= 1 << (slot & 7); }
  // Sorted by slot, because the bitset walk below yields them in that order.
  const values = [...simple].sort((x, y) => slotFor(x.from) - slotFor(y.from))
    .map((row) => encodeIndex(/** @type {number} */ (indexOfPair.get(fieldFor(row))))).join("");

  // The 581 exceptions by shape: `lang-Script`, `lang-Region`, `und-Script-Region`. Anything else
  // keeps its text in full — today that is one row, `und -> en-Latn-US`.
  const isScript = (part) => /^[A-Z][a-z]{3}$/.test(part);
  const groups = [[], [], []], literal = [];
  for (const row of exceptional) {
    const from = row.from.split("-");
    const shape = from.length === 2 ? (isScript(from[1]) ? 0 : 1) : from.length === 3 ? 2 : -1;
    if (shape < 0) literal.push(row); else groups[shape].push(row);
  }
  const languages = (list) => list.map((row) => {
    const from = row.from.split("-"), to = row.to.split("-");
    return from[0] + (to[0] === from[0] ? "" : `>${to[0]}`);
  }).join(" ");
  const indices = (list) => list.map((row) => encodeIndex(/** @type {number} */ (indexOfPair.get(fieldFor(row))))).join("");

  return (
    `const KEYS = ${js(Buffer.from(bits).toString("base64"))};
` +
    `const PAIRS = ${js(alphabet.join(""))};
` +
    `const VALUES = ${js(values)};
` +
    `const BY_SCRIPT = ${js(languages(groups[0]))};
` +
    `const BY_REGION = ${js(languages(groups[1]))};
` +
    `const BY_BOTH = ${js(languages(groups[2]))};
` +
    `const EXCEPTION_VALUES = ${js(indices(groups[0]) + indices(groups[1]) + indices(groups[2]))};
` +
    `const LITERAL = ${js(literal.map((row) => `${row.from}\t${row.to}`).join("\n"))};
` +
    `const SPAN = ${SLOT_SPAN};
` +
    `/** One printable base-91 digit back to its value. */
` +
    `const digit = (/** @type {string} */ s, /** @type {number} */ i) => {
` +
    `  const c = s.charCodeAt(i);
  return (c > 92 ? c - 1 : c) - 35;
};
` +
    `/** The 2-3 letter code a bitset slot stands for. */
` +
    `const codeAt = (/** @type {number} */ slot) => {
` +
    `  const pair = (slot / 27) | 0, third = slot % 27, A = 97;
` +
    `  return third
` +
    `    ? String.fromCharCode(A + ((pair / 26) | 0), A + (pair % 26), A + third - 1)
` +
    `    : String.fromCharCode(A + ((pair / 26) | 0), A + (pair % 26));
};
` +
    `/** @returns {{from: string, to: string}[]} */
` +
    `export const decode = () => {
` +
    `  const bits = Uint8Array.from(atob(KEYS), (c) => c.charCodeAt(0));
` +
    `  /** @param {number} n */
` +
    `  const pairAt = (n) => {
` +
    `    const field = PAIRS.slice(n * 7, n * 7 + 7);
` +
    `    return [field.slice(0, 4), field.charCodeAt(6) === 32 ? field.slice(4, 6) : field.slice(4)];
  };
` +
    `  /** @param {string} stream @param {{ at: number }} cursor */
` +
    `  const indexFrom = (stream, cursor) => {
` +
    `    const first = digit(stream, cursor.at++);
` +
    `    if (first !== 90) return first;
` +
    `    return 90 + digit(stream, cursor.at++) * 91 + digit(stream, cursor.at++);
  };
` +
    `  /** @type {{from: string, to: string}[]} */
  const simple = [];
` +
    `  const walk = { at: 0 };
` +
    `  for (let slot = 0; slot < SPAN; slot++) {
` +
    `    if (!(((bits[slot >> 3] ?? 0) >> (slot & 7)) & 1)) continue;
` +
    `    const from = codeAt(slot);
` +
    `    const [script, region] = pairAt(indexFrom(VALUES, walk));
` +
    `    simple.push({ from, to: \`\${from}-\${script}-\${region}\` });
  }
` +
    `  /** @type {{from: string, to: string}[]} */
  const rest = [];
` +
    `  const other = { at: 0 };
` +
    `  [BY_SCRIPT, BY_REGION, BY_BOTH].forEach((group, shape) => {
` +
    `    if (!group) return;
` +
    `    for (const entry of group.split(" ")) {
` +
    `      const arrow = entry.indexOf(">");
` +
    `      const fromLanguage = arrow < 0 ? entry : entry.slice(0, arrow);
` +
    `      const toLanguage = arrow < 0 ? fromLanguage : entry.slice(arrow + 1);
` +
    `      const [script, region] = pairAt(indexFrom(EXCEPTION_VALUES, other));
` +
    `      const suffix = shape === 0 ? script : shape === 1 ? region : \`\${script}-\${region}\`;
` +
    `      rest.push({ from: \`\${fromLanguage}-\${suffix}\`, to: \`\${toLanguage}-\${script}-\${region}\` });
    }
  });
` +
    `  for (const entry of LITERAL.split("\\n")) {
` +
    `    const tab = entry.indexOf("\\t");
` +
    `    rest.push({ from: entry.slice(0, tab), to: entry.slice(tab + 1) });
  }
` +
    `  rest.sort((x, y) => (x.from < y.from ? -1 : 1));
` +
    `  /** @type {{from: string, to: string}[]} */\n  const out = [];\n` +
    // The helper is the loop bound restated for the checker: `noUncheckedIndexedAccess` cannot see
    // that `a < simple.length` makes `simple[a]` present.
    `  const row = (/** @type {{from: string, to: string}[]} */ list, /** @type {number} */ i) =>\n` +
    `    /** @type {{from: string, to: string}} */ (list[i]);\n` +
    `  let a = 0, b = 0;\n` +
    `  while (a < simple.length && b < rest.length)\n` +
    `    out.push(row(simple, a).from < row(rest, b).from ? row(simple, a++) : row(rest, b++));\n` +
    `  while (a < simple.length) out.push(row(simple, a++));\n` +
    `  while (b < rest.length) out.push(row(rest, b++));\n` +
    `  return out;\n};\n`
  );
};

/** Pair table as row objects. Chosen for parentLocales, where flattening does not pay. */
const rowPairs = (pairs) =>
  `/** @type {{from: string, to: string}[]} */\nconst R = ${js(pairs)};\n` +
  `/** @returns {{from: string, to: string}[]} */\nexport const decode = () => R.map((p) => ({ ...p }));\n`;

/** Plain string set. */
const jsonSet = (values) =>
  `/** @type {string[]} */\nconst S = ${js(values)};\n` +
  `/** @returns {string[]} */\nexport const decode = () => S.slice();\n`;

/**
 * Dense bitset over the two- and three-letter lowercase alphabets. Chosen for validity.languages,
 * where it wins at every compressor level by a wide margin (7,107 -> 1,986 B br-q11).
 */
const bitset = (values) => {
  const planes = { 2: new Uint8Array(Math.ceil(26 ** 2 / 8)), 3: new Uint8Array(Math.ceil(26 ** 3 / 8)) };
  const other = [];
  for (const v of values) {
    if (!/^[a-z]{2,3}$/.test(v)) { other.push(v); continue; }
    const i = [...v].reduce((a, c) => a * 26 + (c.charCodeAt(0) - 97), 0);
    planes[v.length][i >> 3] |= 1 << (i & 7);
  }
  const b64 = (p) => Buffer.from(p).toString("base64");
  return (
    `const T = ${js(b64(planes[2]))};\nconst H = ${js(b64(planes[3]))};\n/** @type {string[]} */\nconst X = ${js(other)};\n` +
    `const bits = (/** @type {string} */ s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));\n` +
    `/** @returns {string[]} */\n` +
    `export const decode = () => {\n` +
    `  /** @type {string[]} */\n  const out = [];\n  const t = bits(T), h = bits(H), A = 97;\n` +
    `  for (let i = 0; i < 676; i++) if (((t[i >> 3] ?? 0) >> (i & 7)) & 1)\n` +
    `    out.push(String.fromCharCode(A + ((i / 26) | 0), A + (i % 26)));\n` +
    `  for (let i = 0; i < 17576; i++) if (((h[i >> 3] ?? 0) >> (i & 7)) & 1)\n` +
    `    out.push(String.fromCharCode(A + ((i / 676) | 0), A + (((i / 26) | 0) % 26), A + (i % 26)));\n` +
    `  return out.concat(X).sort();\n};\n`
  );
};

/** Plural rule groups: locales and rules, conditions kept verbatim for the rule interpreter. */
const ruleGroups = (groups) =>
  `/** @type {[string[], [string, string][]][]} */\n` +
  `const G = ${js(groups.map((g) => [g.locales, g.rules.map((r) => [r.count, r.condition])]))};\n` +
  `/** @returns {{locales: string[], rules: {count: string, condition: string}[]}[]} */\n` +
  `export const decode = () => G.map(([locales, rules]) => ({\n` +
  `  locales: locales.slice(),\n` +
  `  rules: rules.map(([count, condition]) => ({ count, condition })),\n` +
  `}));\n`;

/**
 * Cardinal range groups: locales and (start, end) -> result rows.
 *
 * Ranges are a lookup table, not a rule language: CLDR states the result for each ordered pair of
 * endpoint categories, so there is nothing to interpret at runtime.
 */
const rangeGroups = (groups) =>
  `/** @type {[string[], [string, string, string][]][]} */\n` +
  `const G = ${js(groups.map((g) => [g.locales, g.ranges.map((r) => [r.start, r.end, r.result])]))};\n` +
  `/** @returns {{locales: string[], ranges: {start: string, end: string, result: string}[]}[]} */\n` +
  `export const decode = () => G.map(([locales, ranges]) => ({\n` +
  `  locales: locales.slice(),\n` +
  `  ranges: ranges.map(([start, end, result]) => ({ start, end, result })),\n` +
  `}));\n`;

/**
 * Shared provenance for the OPTIONAL data modules.
 *
 * `lokalized/data/ordinal` and `lokalized/data/ranges` are separately installable, so a consumer can
 * end up pairing an optional module with a root graph generated from different CLDR data. The
 * fingerprint here is the one the spec repo's external lock publishes over the source artifacts, so
 * both sides can compare a single value rather than a hash of their own differing encodings.
 */
const provenance = (source) =>
  `/** @returns {{formatVersion: number, cldrVersion: string, generatorVersion: string, ` +
  `inputsSha256: string, dataFingerprint: string}} */\n` +
  `export const decode = () => (${js(source)});\n`;

const dataLock = JSON.parse(readFileSync(join(specDir, "generated/cldr-data-lock.json"), "utf8"));

/* ------------------------------------------------------------------ modules */

const MODULES = [
  { file: "likely-subtags.js", what: "cldr-locale-data.likelySubtags", source: locale.likelySubtags, encode: maximizationTable },
  { file: "parents.js", what: "cldr-locale-data.parentLocales", source: locale.parentLocales, encode: rowPairs },
  { file: "rtl.js", what: "cldr-locale-data.rightToLeftScripts", source: locale.rightToLeftScripts, encode: jsonSet },
  { file: "aliases-language.js", what: "cldr-locale-data.aliases.language", source: locale.aliases.language, encode: flatPairs },
  { file: "aliases-region.js", what: "cldr-locale-data.aliases.region", source: locale.aliases.region, encode: flatPairs },
  { file: "aliases-script.js", what: "cldr-locale-data.aliases.script", source: locale.aliases.script, encode: rowPairs },
  { file: "aliases-variant.js", what: "cldr-locale-data.aliases.variant", source: locale.aliases.variant, encode: rowPairs },
  { file: "valid-languages.js", what: "cldr-locale-data.validity.languages", source: locale.validity.languages, encode: bitset },
  { file: "valid-scripts.js", what: "cldr-locale-data.validity.scripts", source: locale.validity.scripts, encode: jsonSet },
  { file: "valid-regions.js", what: "cldr-locale-data.validity.regions", source: locale.validity.regions, encode: jsonSet },
  { file: "valid-variants.js", what: "cldr-locale-data.validity.variants", source: locale.validity.variants, encode: jsonSet },
  {
    file: "cardinal.js",
    what: "cldr-plural-data.cardinalRuleGroups",
    // Display examples are deliberately dropped: no public JS API exposes them, and the
    // conformance corpus (not this file) is what gates the selectors.
    source: plural.cardinalRuleGroups.map((g) => ({ locales: g.locales, rules: g.rules.map((r) => ({ count: r.count, condition: r.condition })) })),
    encode: ruleGroups,
  },
  // The two OPTIONAL tables. Emitted as their own modules so the root graph never imports them —
  // scenario 0a's module-count ratchet is what keeps that honest.
  {
    file: "ordinal-rules.js",
    what: "cldr-plural-data.ordinalRuleGroups",
    source: plural.ordinalRuleGroups.map((g) => ({ locales: g.locales, rules: g.rules.map((r) => ({ count: r.count, condition: r.condition })) })),
    encode: ruleGroups,
  },
  {
    file: "cardinal-ranges.js",
    what: "cldr-plural-data.cardinalRangeGroups",
    source: plural.cardinalRangeGroups.map((g) => ({ locales: g.locales, ranges: g.ranges.map((r) => ({ start: r.start, end: r.end, result: r.result })) })),
    encode: rangeGroups,
  },
  {
    file: "provenance.js",
    // ALL FIVE FIELDS PLAN 2.2 DECLARES, not the two the port used to carry.
    //
    // `DataProvenance extends SourceDataProvenance` — `{formatVersion, cldrVersion, generatorVersion,
    // inputsSha256}` plus `dataFingerprint` — and the shipped object carried only `cldrVersion` and
    // `dataFingerprint`. So the two allowlisted TYPE names could not be declared truthfully: writing
    // the plan's shape would have asserted fields `ordinalData.provenance` does not have, and `tsc`
    // would have caught it the moment anything consumed them. The lock has held all five all along;
    // this emits them, which makes the contract and the runtime agree instead of choosing one.
    what: "cldr-data-lock.{formatVersion,cldrVersion,generatorVersion,inputsSha256,dataFingerprint}",
    source: {
      formatVersion: dataLock.formatVersion,
      cldrVersion: dataLock.cldrVersion,
      generatorVersion: dataLock.generatorVersion,
      inputsSha256: dataLock.inputsSha256,
      dataFingerprint: dataLock.dataFingerprint,
    },
    encode: provenance,
  },
];

/**
 * Every canonical field this encoder drops, ENUMERATED AND CHECKED — not merely recorded.
 *
 * WHY THIS IS NOW MACHINE-CHECKED. Plan M1 requires that "justified non-runtime omissions are
 * enumerated", and the M7 row requires that "every M1 assertion that a canonical field is omitted as
 * non-runtime is revalidated against M7's final consumer graph". Until this change, both clauses
 * rested on the PROSE list below being printed by `--measure` and read by a human: no test named it,
 * and `--check` never looked at it.
 *
 * It could not be caught downstream either, and that is the part worth stating plainly.
 * `verifyLossless()` compares `decode()` against `m.source` — but `m.source` is ALREADY the
 * projection, so a canonical field that quietly stopped being omitted, or a NEW field appearing in an
 * upstream CLDR release, round-trips perfectly and changes nothing. The losslessness proof is a proof
 * about the projection, not about the projection being the one that was approved.
 *
 * `verifyOmissions()` closes that by walking the upstream sub-tree each module CLAIMS (its `what`)
 * against the projected `source`, collecting every field present upstream and absent downstream, and
 * requiring that set to equal the declaration here EXACTLY. Both directions fail:
 *
 *   - an upstream field dropped but NOT declared here  -> a silent new omission (a new CLDR field)
 *   - a field declared here but no longer dropped      -> a stale entry, the way known-gap lists rot
 *
 * `omitted: []` is a real assertion, not a placeholder: it says this projection drops nothing, and it
 * fails the moment it starts to.
 */
const NON_RUNTIME_OMISSIONS = [
  {
    from: "cldr-plural-data.cardinalRuleGroups",
    omitted: ["[].rules[].integerExample", "[].rules[].decimalExample"],
    why: "display examples; no public JS API exposes them",
  },
  {
    from: "cldr-plural-data.ordinalRuleGroups",
    omitted: ["[].rules[].integerExample", "[].rules[].decimalExample"],
    why: "display examples; no public JS API exposes them",
  },
  {
    from: "cldr-plural-data.cardinalRangeGroups",
    omitted: [],
    why: "nothing is dropped; CLDR states start/end/result and all three ship",
  },
  {
    from: "cldr-conformance-vectors.json",
    omitted: ["entire artifact"],
    why: "test-time corpus; never shipped in the runtime graph",
    wholeArtifact: true,
  },
];

/**
 * Field paths present in `upstream` and absent from `projected`, compared in parallel.
 *
 * Arrays are compared element-wise and their per-element key sets unioned, so a field that appears on
 * only some rules is still seen. Only the SHAPE is compared; values are `verifyLossless()`'s job.
 *
 * @param {unknown} upstream
 * @param {unknown} projected
 * @param {string} path
 * @param {Set<string>} into
 */
function collectDroppedFields(upstream, projected, path, into) {
  if (Array.isArray(upstream)) {
    if (!Array.isArray(projected)) return;
    for (let i = 0; i < upstream.length; ++i)
      collectDroppedFields(upstream[i], projected[i], `${path}[]`, into);
    return;
  }

  if (upstream === null || typeof upstream !== "object") return;
  if (projected === null || typeof projected !== "object" || Array.isArray(projected)) return;

  for (const key of Object.keys(upstream)) {
    const where = path ? `${path}.${key}` : key;
    if (!(key in projected)) {
      into.add(where);
      continue;
    }
    collectDroppedFields(
      /** @type {any} */ (upstream)[key],
      /** @type {any} */ (projected)[key],
      where,
      into,
    );
  }
}

/** Resolves a `what` like `cldr-plural-data.cardinalRuleGroups` to the live upstream sub-tree. */
function upstreamSubtree(what) {
  const [artifact, ...rest] = what.split(".");
  const roots = { "cldr-plural-data": plural, "cldr-locale-data": locale };
  let node = /** @type {any} */ (roots)[artifact];
  for (const segment of rest) node = node?.[segment];
  return node;
}

/**
 * Revalidates every declared non-runtime omission against the CURRENT upstream artifacts.
 *
 * @returns {string[]} problems, empty when every declaration is exact
 */
function verifyOmissions() {
  const problems = [];

  for (const omission of NON_RUNTIME_OMISSIONS) {
    if (omission.wholeArtifact) {
      // A whole artifact is omitted by never being sourced. Assert that literally, so "we do not ship
      // the conformance vectors" cannot quietly become false by a module starting to read them.
      const path = join(specDir, "vendor/lokalized-java/src/build/resources/cldr", omission.from);
      if (!existsSync(path))
        problems.push(`${omission.from}: declared omitted, but no such upstream artifact exists — stale declaration`);
      if (MODULES.some((m) => m.what.startsWith(omission.from.replace(/\.json$/, ""))))
        problems.push(`${omission.from}: declared omitted, but a generated module now sources it`);
      continue;
    }

    const module = MODULES.find((m) => m.what === omission.from);
    if (!module) {
      problems.push(`${omission.from}: declared omitted, but no generated module claims that sub-tree — stale declaration`);
      continue;
    }

    const upstream = upstreamSubtree(omission.from);
    if (upstream === undefined) {
      problems.push(`${omission.from}: not present in the pinned upstream artifact — stale declaration`);
      continue;
    }

    /** @type {Set<string>} */
    const dropped = new Set();
    collectDroppedFields(upstream, module.source, "", dropped);

    const found = [...dropped].sort();
    const declared = [...omission.omitted].sort();
    if (JSON.stringify(found) !== JSON.stringify(declared))
      problems.push(
        `${omission.from}: the fields this encoder actually drops have changed.\n` +
          `       declared: ${declared.length ? declared.join(", ") : "(none)"}\n` +
          `       measured: ${found.length ? found.join(", ") : "(none)"}\n` +
          `       An undeclared drop is a new non-runtime omission that nobody approved; a declared ` +
          `drop that no longer happens is a stale entry.`,
      );
  }

  return problems;
}

/* ------------------------------------------------------------------ run */

const gzip = (t) => gzipSync(Buffer.from(t, "utf8"), { level: 9 }).byteLength;
const br = (t, q) => brotliCompressSync(Buffer.from(t, "utf8"), { params: { [constants.BROTLI_PARAM_QUALITY]: q } }).byteLength;

const emitted = MODULES.map((m) => ({ ...m, text: banner(m.what) + m.encode(m.source) }));

/** Import each emitted module and prove its decode() reproduces the source's canonical bytes. */
async function verifyLossless() {
  const work = await mkdtemp(join(tmpdir(), "lokalized-gen-"));
  const failures = [];
  // Removed in a `finally`: an emitted module that does not import used to leave the directory behind.
  try {
    for (const m of emitted) {
      const p = join(work, m.file.replace(/\.js$/, ".mjs"));
      await writeFile(p, m.text);
      const { decode } = await import(`file://${p}`);
      if (jcs(decode()) !== jcs(m.source)) failures.push(`${m.file}: decode() does not reproduce the source`);
    }

    // Likely subtags carry extra obligations the generic round-trip does not express.
    const p = join(work, "ls.mjs");
    await writeFile(p, emitted.find((m) => m.file === "likely-subtags.js").text);
    const rows = (await import(`file://${p}`)).decode();
    const byKey = new Map(rows.map((r) => [r.from, r.to]));
    if (byKey.size !== locale.likelySubtags.length) failures.push("likely-subtags: key count changed");
    for (const { from, to } of locale.likelySubtags) {
      if (byKey.get(from) !== to) failures.push(`likely-subtags: ${from} triple not preserved`);
      if (to.split("-").length < 3) failures.push(`likely-subtags: ${from} lost a triple component`);
    }
    if (byKey.has("zz-not-a-key")) failures.push("likely-subtags: absent key resolves");
    const latn = locale.likelySubtags.find((r) => r.to.includes("-Latn-"));
    if (latn && !byKey.has(latn.from)) failures.push("likely-subtags: present Latn row lost its presence bit");
  } finally {
    await rm(work, { recursive: true, force: true });
  }
  return failures;
}

const mode = process.argv.includes("--write") ? "write" : process.argv.includes("--check") ? "check" : process.argv.includes("--measure") ? "measure" : null;

if (mode === "measure") {
  const all = emitted.map((m) => m.text).join("\n");
  console.log(`integrated derivative, CLDR ${locale.cldrVersion}\n`);
  console.log(`${"module".padEnd(22)}${"raw".padStart(9)}${"gzip-9".padStart(9)}${"br-q11".padStart(9)}${"br-q5".padStart(9)}`);
  for (const m of emitted) {
    const t = m.text;
    console.log(m.file.padEnd(22) + String(Buffer.byteLength(t)).padStart(9) + String(gzip(t)).padStart(9) + String(br(t, 11)).padStart(9) + String(br(t, 5)).padStart(9));
  }
  console.log("-".repeat(58));
  console.log("sum of parts".padEnd(22) + String(emitted.reduce((n, m) => n + Buffer.byteLength(m.text), 0)).padStart(9) + String(emitted.reduce((n, m) => n + gzip(m.text), 0)).padStart(9) + String(emitted.reduce((n, m) => n + br(m.text, 11), 0)).padStart(9) + String(emitted.reduce((n, m) => n + br(m.text, 5), 0)).padStart(9));
  console.log("INTEGRATED".padEnd(22) + String(Buffer.byteLength(all)).padStart(9) + String(gzip(all)).padStart(9) + String(br(all, 11)).padStart(9) + String(br(all, 5)).padStart(9));
  console.log("\nIntegrated is the figure that matters: one compression window is shared across tables,");
  console.log("so the sum of independently-compressed parts overstates the real cost.");
  console.log("\nNon-runtime omissions:");
  for (const o of NON_RUNTIME_OMISSIONS)
    console.log(`  ${o.from}: ${o.omitted.length ? o.omitted.join(", ") : "(nothing dropped)"}\n     ${o.why}`);
} else if (mode === "write") {
  const failures = [...(await verifyLossless()), ...verifyOmissions()];
  if (failures.length) {
    console.error(`refusing to write; ${failures.length} losslessness/omission failure(s):`);
    for (const f of failures) console.error(`  ${f}`);
    process.exit(1);
  }
  for (const m of emitted) await writeFile(join(outDir, m.file), m.text);
  console.log(JSON.stringify({ status: "written", modules: emitted.length, cldrVersion: locale.cldrVersion }));
} else if (mode === "check") {
  const problems = [];
  for (const m of emitted) {
    let onDisk;
    try {
      onDisk = await readFile(join(outDir, m.file), "utf8");
    } catch {
      problems.push(`${m.file}: missing; run --write`);
      continue;
    }
    if (onDisk !== m.text) problems.push(`${m.file}: on-disk bytes differ from regeneration`);
  }
  problems.push(...(await verifyLossless()));
  problems.push(...verifyOmissions());
  if (problems.length) {
    console.error(JSON.stringify({ status: "stale-or-lossy", problems }, null, 2));
    process.exit(1);
  }
  console.log(JSON.stringify({
    status: "current",
    modules: emitted.length,
    lossless: true,
    // Reported as its own field so a reader can see the M1 omission clause was revalidated on THIS
    // run against THESE upstream artifacts, rather than inferred from the absence of a complaint.
    omissionsRevalidated: NON_RUNTIME_OMISSIONS.length,
    cldrVersion: locale.cldrVersion,
  }));
} else {
  console.error("usage: node tools/gen-data.js --write | --check | --measure");
  process.exit(2);
}
