#!/usr/bin/env node
// @ts-check
/**
 * Production data encoder: pinned CLDR JSON -> runtime JavaScript modules.
 *
 * Reads the SHA-pinned artifacts vendored in the sibling lokalized-spec checkout and emits
 * `src/data/*.js`. This tool carries no CLDR knowledge: every semantic decision was made upstream
 * by CldrDataGenerator, and every encoding decision is recorded in the planning directory's ENCODING-DECISION.md.
 *
 * Guarantees, all verified by `--check`:
 *   - LOSSLESS: each emitted module is imported, decoded, and its canonical JCS projection compared
 *     byte-for-byte against the same projection of the source. Not a shape check — exact bytes.
 *   - Likely subtags additionally preserve every key, the full language-script-region triple, the
 *     presence bit, and absent/unknown behavior. Row absence and a present Latn row stay distinct.
 *   - REPRODUCIBLE: regeneration is byte-identical.
 *
 *   node tools/gen-data.js --write    emit modules
 *   node tools/gen-data.js --check    verify emitted modules are current, lossless and reproducible
 *   node tools/gen-data.js --measure  integrated size table (raw/min-ish/gzip-9/br-q11/br-q5)
 */
import { brotliCompressSync, constants, gzipSync } from "node:zlib";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const specDir = process.env.LOKALIZED_SPEC_DIR
  ? resolve(process.env.LOKALIZED_SPEC_DIR)
  : resolve(root, "../lokalized-spec");
const vendor = join(specDir, "vendor/lokalized-java/src/build/resources/cldr");
const outDir = join(root, "src/data");

if (!existsSync(vendor)) {
  console.error(`cannot find vendored CLDR artifacts at ${vendor}\nclone lokalized-spec as a sibling, or set LOKALIZED_SPEC_DIR`);
  process.exit(2);
}

const locale = JSON.parse(readFileSync(join(vendor, "cldr-locale-data.json"), "utf8"));
const plural = JSON.parse(readFileSync(join(vendor, "cldr-plural-data.json"), "utf8"));

/** Canonical JSON: sorted object keys, no whitespace. Matches the upstream generator exactly. */
const jcs = (value) => {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(jcs).join(",")}]`;
  return `{${Object.keys(value).sort().map((k) => `${JSON.stringify(k)}:${jcs(value[k])}`).join(",")}}`;
};

const js = (v) => JSON.stringify(v);
const banner = (what) =>
  `// Generated by tools/gen-data.js from pinned CLDR ${locale.cldrVersion}. Do not edit by hand.\n` +
  `// Source: lokalized-spec vendor/lokalized-java (${what}).\n` +
  `// Contains data derived from Unicode CLDR, licensed under Unicode License v3. See NOTICE.\n`;

/* ------------------------------------------------------------------ encoders
 * Selected per the planning directory's ENCODING-DECISION.md, which chose by best Brotli-q5 because
 * dynamic CDN compression is the production-realistic case and the q11 penalty is negligible.
 */

/** Pair table as one flat array. Chosen for likelySubtags and the language/region alias tables. */
const flatPairs = (pairs) =>
  `/** @type {string[]} */\nconst F = ${js(pairs.flatMap((p) => [p.from, p.to]))};\n` +
  `/** @returns {{from: string, to: string}[]} */\n` +
  `export const decode = () => {\n` +
  `  /** @type {{from: string, to: string}[]} */\n  const out = [];\n` +
  `  for (let i = 0; i < F.length; i += 2) out.push({ from: /** @type {string} */ (F[i]), to: /** @type {string} */ (F[i + 1]) });\n` +
  `  return out;\n};\n`;

/** Pair table as row objects. Chosen for parentLocales, where flattening does not pay. */
const rowPairs = (pairs) =>
  `/** @type {{from: string, to: string}[]} */\nconst R = ${js(pairs)};\n` +
  `/** @returns {{from: string, to: string}[]} */\nexport const decode = () => R.map((p) => ({ ...p }));\n`;

/** Plain string set. */
const jsonSet = (values) =>
  `/** @type {string[]} */\nconst S = ${js(values)};\n` +
  `/** @returns {string[]} */\nexport const decode = () => S.slice();\n`;

/**
 * Dense bitset over the two- and three-letter lowercase alphabets. Chosen for validity.languages,
 * where it wins at every compressor level by a wide margin (7,107 -> 1,986 B br-q11).
 */
const bitset = (values) => {
  const planes = { 2: new Uint8Array(Math.ceil(26 ** 2 / 8)), 3: new Uint8Array(Math.ceil(26 ** 3 / 8)) };
  const other = [];
  for (const v of values) {
    if (!/^[a-z]{2,3}$/.test(v)) { other.push(v); continue; }
    const i = [...v].reduce((a, c) => a * 26 + (c.charCodeAt(0) - 97), 0);
    planes[v.length][i >> 3] |= 1 << (i & 7);
  }
  const b64 = (p) => Buffer.from(p).toString("base64");
  return (
    `const T = ${js(b64(planes[2]))};\nconst H = ${js(b64(planes[3]))};\n/** @type {string[]} */\nconst X = ${js(other)};\n` +
    `const bits = (/** @type {string} */ s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));\n` +
    `/** @returns {string[]} */\n` +
    `export const decode = () => {\n` +
    `  /** @type {string[]} */\n  const out = [];\n  const t = bits(T), h = bits(H), A = 97;\n` +
    `  for (let i = 0; i < 676; i++) if (((t[i >> 3] ?? 0) >> (i & 7)) & 1)\n` +
    `    out.push(String.fromCharCode(A + ((i / 26) | 0), A + (i % 26)));\n` +
    `  for (let i = 0; i < 17576; i++) if (((h[i >> 3] ?? 0) >> (i & 7)) & 1)\n` +
    `    out.push(String.fromCharCode(A + ((i / 676) | 0), A + (((i / 26) | 0) % 26), A + (i % 26)));\n` +
    `  return out.concat(X).sort();\n};\n`
  );
};

/** Plural rule groups: locales and rules, conditions kept verbatim for the rule interpreter. */
const ruleGroups = (groups) =>
  `/** @type {[string[], [string, string][]][]} */\n` +
  `const G = ${js(groups.map((g) => [g.locales, g.rules.map((r) => [r.count, r.condition])]))};\n` +
  `/** @returns {{locales: string[], rules: {count: string, condition: string}[]}[]} */\n` +
  `export const decode = () => G.map(([locales, rules]) => ({\n` +
  `  locales: locales.slice(),\n` +
  `  rules: rules.map(([count, condition]) => ({ count, condition })),\n` +
  `}));\n`;

/**
 * Cardinal range groups: locales and (start, end) -> result rows.
 *
 * Ranges are a lookup table, not a rule language: CLDR states the result for each ordered pair of
 * endpoint categories, so there is nothing to interpret at runtime.
 */
const rangeGroups = (groups) =>
  `/** @type {[string[], [string, string, string][]][]} */\n` +
  `const G = ${js(groups.map((g) => [g.locales, g.ranges.map((r) => [r.start, r.end, r.result])]))};\n` +
  `/** @returns {{locales: string[], ranges: {start: string, end: string, result: string}[]}[]} */\n` +
  `export const decode = () => G.map(([locales, ranges]) => ({\n` +
  `  locales: locales.slice(),\n` +
  `  ranges: ranges.map(([start, end, result]) => ({ start, end, result })),\n` +
  `}));\n`;

/**
 * Shared provenance for the OPTIONAL data modules.
 *
 * `lokalized/data/ordinal` and `lokalized/data/ranges` are separately installable, so a consumer can
 * end up pairing an optional module with a root graph generated from different CLDR data. The
 * fingerprint here is the one the spec repo's external lock publishes over the source artifacts, so
 * both sides can compare a single value rather than a hash of their own differing encodings.
 */
const provenance = (source) =>
  `/** @returns {{cldrVersion: string, dataFingerprint: string}} */\n` +
  `export const decode = () => (${js(source)});\n`;

const dataLock = JSON.parse(readFileSync(join(specDir, "generated/cldr-data-lock.json"), "utf8"));

/* ------------------------------------------------------------------ modules */

const MODULES = [
  { file: "likely-subtags.js", what: "cldr-locale-data.likelySubtags", source: locale.likelySubtags, encode: flatPairs },
  { file: "parents.js", what: "cldr-locale-data.parentLocales", source: locale.parentLocales, encode: rowPairs },
  { file: "rtl.js", what: "cldr-locale-data.rightToLeftScripts", source: locale.rightToLeftScripts, encode: jsonSet },
  { file: "aliases-language.js", what: "cldr-locale-data.aliases.language", source: locale.aliases.language, encode: flatPairs },
  { file: "aliases-region.js", what: "cldr-locale-data.aliases.region", source: locale.aliases.region, encode: flatPairs },
  { file: "aliases-script.js", what: "cldr-locale-data.aliases.script", source: locale.aliases.script, encode: rowPairs },
  { file: "aliases-variant.js", what: "cldr-locale-data.aliases.variant", source: locale.aliases.variant, encode: rowPairs },
  { file: "valid-languages.js", what: "cldr-locale-data.validity.languages", source: locale.validity.languages, encode: bitset },
  { file: "valid-scripts.js", what: "cldr-locale-data.validity.scripts", source: locale.validity.scripts, encode: jsonSet },
  { file: "valid-regions.js", what: "cldr-locale-data.validity.regions", source: locale.validity.regions, encode: jsonSet },
  { file: "valid-variants.js", what: "cldr-locale-data.validity.variants", source: locale.validity.variants, encode: jsonSet },
  {
    file: "cardinal.js",
    what: "cldr-plural-data.cardinalRuleGroups",
    // Display examples are deliberately dropped: no public JS API exposes them, and the
    // conformance corpus (not this file) is what gates the selectors.
    source: plural.cardinalRuleGroups.map((g) => ({ locales: g.locales, rules: g.rules.map((r) => ({ count: r.count, condition: r.condition })) })),
    encode: ruleGroups,
  },
  // The two OPTIONAL tables. Emitted as their own modules so the root graph never imports them —
  // scenario 0a's module-count ratchet is what keeps that honest.
  {
    file: "ordinal-rules.js",
    what: "cldr-plural-data.ordinalRuleGroups",
    source: plural.ordinalRuleGroups.map((g) => ({ locales: g.locales, rules: g.rules.map((r) => ({ count: r.count, condition: r.condition })) })),
    encode: ruleGroups,
  },
  {
    file: "cardinal-ranges.js",
    what: "cldr-plural-data.cardinalRangeGroups",
    source: plural.cardinalRangeGroups.map((g) => ({ locales: g.locales, ranges: g.ranges.map((r) => ({ start: r.start, end: r.end, result: r.result })) })),
    encode: rangeGroups,
  },
  {
    file: "provenance.js",
    what: "cldr-data-lock.{cldrVersion,dataFingerprint}",
    source: { cldrVersion: dataLock.cldrVersion, dataFingerprint: dataLock.dataFingerprint },
    encode: provenance,
  },
];

/**
 * Every canonical field this encoder drops, ENUMERATED AND CHECKED — not merely recorded.
 *
 * WHY THIS IS NOW MACHINE-CHECKED. Plan M1 requires that "justified non-runtime omissions are
 * enumerated", and the M7 row requires that "every M1 assertion that a canonical field is omitted as
 * non-runtime is revalidated against M7's final consumer graph". Until this change, both clauses
 * rested on the PROSE list below being printed by `--measure` and read by a human: no test named it,
 * and `--check` never looked at it.
 *
 * It could not be caught downstream either, and that is the part worth stating plainly.
 * `verifyLossless()` compares `decode()` against `m.source` — but `m.source` is ALREADY the
 * projection, so a canonical field that quietly stopped being omitted, or a NEW field appearing in an
 * upstream CLDR release, round-trips perfectly and changes nothing. The losslessness proof is a proof
 * about the projection, not about the projection being the one that was approved.
 *
 * `verifyOmissions()` closes that by walking the upstream sub-tree each module CLAIMS (its `what`)
 * against the projected `source`, collecting every field present upstream and absent downstream, and
 * requiring that set to equal the declaration here EXACTLY. Both directions fail:
 *
 *   - an upstream field dropped but NOT declared here  -> a silent new omission (a new CLDR field)
 *   - a field declared here but no longer dropped      -> a stale entry, the way known-gap lists rot
 *
 * `omitted: []` is a real assertion, not a placeholder: it says this projection drops nothing, and it
 * fails the moment it starts to.
 */
const NON_RUNTIME_OMISSIONS = [
  {
    from: "cldr-plural-data.cardinalRuleGroups",
    omitted: ["[].rules[].integerExample", "[].rules[].decimalExample"],
    why: "display examples; no public JS API exposes them",
  },
  {
    from: "cldr-plural-data.ordinalRuleGroups",
    omitted: ["[].rules[].integerExample", "[].rules[].decimalExample"],
    why: "display examples; no public JS API exposes them",
  },
  {
    from: "cldr-plural-data.cardinalRangeGroups",
    omitted: [],
    why: "nothing is dropped; CLDR states start/end/result and all three ship",
  },
  {
    from: "cldr-conformance-vectors.json",
    omitted: ["entire artifact"],
    why: "test-time corpus; never shipped in the runtime graph",
    wholeArtifact: true,
  },
];

/**
 * Field paths present in `upstream` and absent from `projected`, compared in parallel.
 *
 * Arrays are compared element-wise and their per-element key sets unioned, so a field that appears on
 * only some rules is still seen. Only the SHAPE is compared; values are `verifyLossless()`'s job.
 *
 * @param {unknown} upstream
 * @param {unknown} projected
 * @param {string} path
 * @param {Set<string>} into
 */
function collectDroppedFields(upstream, projected, path, into) {
  if (Array.isArray(upstream)) {
    if (!Array.isArray(projected)) return;
    for (let i = 0; i < upstream.length; ++i)
      collectDroppedFields(upstream[i], projected[i], `${path}[]`, into);
    return;
  }

  if (upstream === null || typeof upstream !== "object") return;
  if (projected === null || typeof projected !== "object" || Array.isArray(projected)) return;

  for (const key of Object.keys(upstream)) {
    const where = path ? `${path}.${key}` : key;
    if (!(key in projected)) {
      into.add(where);
      continue;
    }
    collectDroppedFields(
      /** @type {any} */ (upstream)[key],
      /** @type {any} */ (projected)[key],
      where,
      into,
    );
  }
}

/** Resolves a `what` like `cldr-plural-data.cardinalRuleGroups` to the live upstream sub-tree. */
function upstreamSubtree(what) {
  const [artifact, ...rest] = what.split(".");
  const roots = { "cldr-plural-data": plural, "cldr-locale-data": locale };
  let node = /** @type {any} */ (roots)[artifact];
  for (const segment of rest) node = node?.[segment];
  return node;
}

/**
 * Revalidates every declared non-runtime omission against the CURRENT upstream artifacts.
 *
 * @returns {string[]} problems, empty when every declaration is exact
 */
function verifyOmissions() {
  const problems = [];

  for (const omission of NON_RUNTIME_OMISSIONS) {
    if (omission.wholeArtifact) {
      // A whole artifact is omitted by never being sourced. Assert that literally, so "we do not ship
      // the conformance vectors" cannot quietly become false by a module starting to read them.
      const path = join(specDir, "vendor/lokalized-java/src/build/resources/cldr", omission.from);
      if (!existsSync(path))
        problems.push(`${omission.from}: declared omitted, but no such upstream artifact exists — stale declaration`);
      if (MODULES.some((m) => m.what.startsWith(omission.from.replace(/\.json$/, ""))))
        problems.push(`${omission.from}: declared omitted, but a generated module now sources it`);
      continue;
    }

    const module = MODULES.find((m) => m.what === omission.from);
    if (!module) {
      problems.push(`${omission.from}: declared omitted, but no generated module claims that sub-tree — stale declaration`);
      continue;
    }

    const upstream = upstreamSubtree(omission.from);
    if (upstream === undefined) {
      problems.push(`${omission.from}: not present in the pinned upstream artifact — stale declaration`);
      continue;
    }

    /** @type {Set<string>} */
    const dropped = new Set();
    collectDroppedFields(upstream, module.source, "", dropped);

    const found = [...dropped].sort();
    const declared = [...omission.omitted].sort();
    if (JSON.stringify(found) !== JSON.stringify(declared))
      problems.push(
        `${omission.from}: the fields this encoder actually drops have changed.\n` +
          `       declared: ${declared.length ? declared.join(", ") : "(none)"}\n` +
          `       measured: ${found.length ? found.join(", ") : "(none)"}\n` +
          `       An undeclared drop is a new non-runtime omission that nobody approved; a declared ` +
          `drop that no longer happens is a stale entry.`,
      );
  }

  return problems;
}

/* ------------------------------------------------------------------ run */

const gzip = (t) => gzipSync(Buffer.from(t, "utf8"), { level: 9 }).byteLength;
const br = (t, q) => brotliCompressSync(Buffer.from(t, "utf8"), { params: { [constants.BROTLI_PARAM_QUALITY]: q } }).byteLength;

const emitted = MODULES.map((m) => ({ ...m, text: banner(m.what) + m.encode(m.source) }));

/** Import each emitted module and prove its decode() reproduces the source's canonical bytes. */
async function verifyLossless() {
  const work = await mkdtemp(join(tmpdir(), "lokalized-gen-"));
  const failures = [];
  for (const m of emitted) {
    const p = join(work, m.file.replace(/\.js$/, ".mjs"));
    await writeFile(p, m.text);
    const { decode } = await import(`file://${p}`);
    if (jcs(decode()) !== jcs(m.source)) failures.push(`${m.file}: decode() does not reproduce the source`);
  }

  // Likely subtags carry extra obligations the generic round-trip does not express.
  const p = join(work, "ls.mjs");
  await writeFile(p, emitted.find((m) => m.file === "likely-subtags.js").text);
  const rows = (await import(`file://${p}`)).decode();
  const byKey = new Map(rows.map((r) => [r.from, r.to]));
  if (byKey.size !== locale.likelySubtags.length) failures.push("likely-subtags: key count changed");
  for (const { from, to } of locale.likelySubtags) {
    if (byKey.get(from) !== to) failures.push(`likely-subtags: ${from} triple not preserved`);
    if (to.split("-").length < 3) failures.push(`likely-subtags: ${from} lost a triple component`);
  }
  if (byKey.has("zz-not-a-key")) failures.push("likely-subtags: absent key resolves");
  const latn = locale.likelySubtags.find((r) => r.to.includes("-Latn-"));
  if (latn && !byKey.has(latn.from)) failures.push("likely-subtags: present Latn row lost its presence bit");

  await rm(work, { recursive: true, force: true });
  return failures;
}

const mode = process.argv.includes("--write") ? "write" : process.argv.includes("--check") ? "check" : process.argv.includes("--measure") ? "measure" : null;

if (mode === "measure") {
  const all = emitted.map((m) => m.text).join("\n");
  console.log(`integrated derivative, CLDR ${locale.cldrVersion}\n`);
  console.log(`${"module".padEnd(22)}${"raw".padStart(9)}${"gzip-9".padStart(9)}${"br-q11".padStart(9)}${"br-q5".padStart(9)}`);
  for (const m of emitted) {
    const t = m.text;
    console.log(m.file.padEnd(22) + String(Buffer.byteLength(t)).padStart(9) + String(gzip(t)).padStart(9) + String(br(t, 11)).padStart(9) + String(br(t, 5)).padStart(9));
  }
  console.log("-".repeat(58));
  console.log("sum of parts".padEnd(22) + String(emitted.reduce((n, m) => n + Buffer.byteLength(m.text), 0)).padStart(9) + String(emitted.reduce((n, m) => n + gzip(m.text), 0)).padStart(9) + String(emitted.reduce((n, m) => n + br(m.text, 11), 0)).padStart(9) + String(emitted.reduce((n, m) => n + br(m.text, 5), 0)).padStart(9));
  console.log("INTEGRATED".padEnd(22) + String(Buffer.byteLength(all)).padStart(9) + String(gzip(all)).padStart(9) + String(br(all, 11)).padStart(9) + String(br(all, 5)).padStart(9));
  console.log("\nIntegrated is the figure that matters: one compression window is shared across tables,");
  console.log("so the sum of independently-compressed parts overstates the real cost.");
  console.log("\nNon-runtime omissions:");
  for (const o of NON_RUNTIME_OMISSIONS)
    console.log(`  ${o.from}: ${o.omitted.length ? o.omitted.join(", ") : "(nothing dropped)"}\n     ${o.why}`);
} else if (mode === "write") {
  const failures = [...(await verifyLossless()), ...verifyOmissions()];
  if (failures.length) {
    console.error(`refusing to write; ${failures.length} losslessness/omission failure(s):`);
    for (const f of failures) console.error(`  ${f}`);
    process.exit(1);
  }
  for (const m of emitted) await writeFile(join(outDir, m.file), m.text);
  console.log(JSON.stringify({ status: "written", modules: emitted.length, cldrVersion: locale.cldrVersion }));
} else if (mode === "check") {
  const problems = [];
  for (const m of emitted) {
    let onDisk;
    try {
      onDisk = await readFile(join(outDir, m.file), "utf8");
    } catch {
      problems.push(`${m.file}: missing; run --write`);
      continue;
    }
    if (onDisk !== m.text) problems.push(`${m.file}: on-disk bytes differ from regeneration`);
  }
  problems.push(...(await verifyLossless()));
  problems.push(...verifyOmissions());
  if (problems.length) {
    console.error(JSON.stringify({ status: "stale-or-lossy", problems }, null, 2));
    process.exit(1);
  }
  console.log(JSON.stringify({
    status: "current",
    modules: emitted.length,
    lossless: true,
    // Reported as its own field so a reader can see the M1 omission clause was revalidated on THIS
    // run against THESE upstream artifacts, rather than inferred from the absence of a complaint.
    omissionsRevalidated: NON_RUNTIME_OMISSIONS.length,
    cldrVersion: locale.cldrVersion,
  }));
} else {
  console.error("usage: node tools/gen-data.js --write | --check | --measure");
  process.exit(2);
}
